x-common-variables: &common-variables
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1
  LOG_LEVEL: ${LOG_LEVEL:-INFO}

x-service-common: &service-common
  restart: unless-stopped
  networks:
    - grocery_finder_network
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 512M
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  api_gateway:
    <<: *service-common
    container_name: grocery_finder_api_gateway
    build:
      context: ../services/api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      <<: *common-variables
      AUTH_SERVICE_URL: http://auth_service:8000
      USER_SERVICE_URL: http://user_service:8000
      PRICE_SERVICE_URL: http://price_service:8000
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      RATE_LIMIT_PER_MINUTE: ${RATE_LIMIT_PER_MINUTE}
      REDIS_URL: redis://redis:6379
    volumes:
      - ../services/api_gateway:/app:ro
      - api_gateway_logs:/var/log/api_gateway
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - grocery_finder_network

  auth_service:
    <<: *service-common
    container_name: grocery_finder_auth_service
    build:
      context: ../services/auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      <<: *common-variables
      MONGODB_URL: mongodb://mongodb:27017/${MONGODB_DATABASE}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS:-12}
    volumes:
      - ../services/auth_service:/app:ro
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - grocery_finder_network

  user_service:
    <<: *service-common
    container_name: grocery_finder_user_service
    build:
      context: ../services/user_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      <<: *common-variables
      DATABASE_URL: postgresql://josuejero:peruano1@postgres:5432/grocery_finder
      POSTGRES_USER: josuejero
      POSTGRES_PASSWORD: peruano1
      POSTGRES_DB: grocery_finder
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET_KEY: cf00a032a7d8943e4e569105b95087b382b31153c3d7aad6138a173da04f89f3
      JWT_ALGORITHM: HS256
      AUTH_SERVICE_URL: http://auth_service:8000
    volumes:
      - ../services/user_service:/app:ro
      - user_service_logs:/var/log/user_service
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - grocery_finder_network

  price_service:
    <<: *service-common
    container_name: grocery_finder_price_service
    build:
      context: ../services/price_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      <<: *common-variables
      MONGODB_URL: mongodb://mongodb:27017/${MONGODB_DATABASE}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - ../services/price_service:/app:ro
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - grocery_finder_network

  mongodb:
    image: mongo:5.0
    container_name: grocery_finder_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    command: mongod --bind_ip_all
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - grocery_finder_network

  redis:
    image: redis:7-alpine
    container_name: grocery_finder_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - grocery_finder_network

  postgres:
    image: postgres:14-alpine
    container_name: grocery_finder_postgres
    environment:
      POSTGRES_USER: josuejero
      POSTGRES_PASSWORD: peruano1
      POSTGRES_DB: grocery_finder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U josuejero -d grocery_finder"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - grocery_finder_network

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
  user_service_logs:
  api_gateway_logs:

networks:
  grocery_finder_network:
    driver: bridge